### ISSUE TITLE
Error code 1 is returned when there are no unused steps in the project

### ISSUE THREAD

**Issue by RRaulAndrei** [alexmalimon/TestReporter.SpecFlow.Tool#2]
Hi!
We are tying to use your tool with our AQA project and we want to add a validation that will be executed at each pull-request, to be sure that there are no unused steps in the project. However, the problem is that when the result is **0 unused steps**, **we get an error response**. This is not helping us because we need to receive a successfully response when there are no unused steps. Right now we get **error code 0 when there are unused steps** and **error code 1 when there are not.**

This is the output when there are 0 unused steps:
[Information] Finished extracting information about generated feature's code
[Error] No step definitions have been found.
An error occurred when executing task 'SpecflowStepDefinitionReport'.
Error: One or more errors occurred. (Process specflow-report --project <project name> --output <output location> failed with code 1)
        Process specflow-report --project <project name> --output <output location> failed with code 1

Thank you for your help!

**Comment by alexmalimon** [comment]
Hi @RRaulAndrei,
Thank you for noticing this. 
I will fix it in a few days.

**Comment by alexmalimon** [comment]
Closing this issue as it is now fixed in 2.3.1 version.
