### ISSUE TITLE
Tool not compatible with netCore 3.1 project

### ISSUE THREAD

**Issue by bogdanChernichenko** [alexmalimon/TestReporter.SpecFlow.Tool#3]

**Comment by alexmalimon** [comment]
Hi @bogdanChernichenko!
Could you please provide some examples or steps to reproduce? I've just tested latest tool version (2.4.1) with one of the projects from [SpecFlow-Examples](https://github.com/SpecFlowOSS/SpecFlow-Examples) that has `<TargetFramework>netcoreapp3.1</TargetFramework>` and everything worked as expected.

**Comment by bogdanChernichenko** [comment]
Hey, just tried on my project with
<TargetFramework>netcoreapp3.1</TargetFramework>
And here is exceptions list that I've got:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Package 'TestReporter.SpecFlow.Tool 2.4.1' has a package type 'DotnetTool' that is not supported by project 'MyProj'.				


Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package TestReporter.SpecFlow.Tool 2.4.1 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package TestReporter.SpecFlow.Tool 2.4.1 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any	MyProj	D:\MyProj.csproj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1212	Invalid project-package combination for TestReporter.SpecFlow.Tool 2.4.1. DotnetToolReference project style can only contain references of the DotnetTool type 	MyProj	D:\MyProj.csproj	1

**Comment by alexmalimon** [comment]
> Error Package 'TestReporter.SpecFlow.Tool 2.4.1' has a package type 'DotnetTool' that is not supported by project 'MyProj'.

Wait, have you added it as PackageReference?

**Comment by bogdanChernichenko** [comment]
I've added it via Nuget package manager

**Comment by alexmalimon** [comment]
> I've added it via Nuget package manager

You have to install it as .Net tool with this commad `dotnet tool install --global TestReporter.SpecFlow.Tool --version 2.4.1`. After installation it will be available to use.  
In project folder (where csproj file is located) you have to run `specflow-reporter -p ".\" -o "output folder path"`. As a result in output folder will be *.html report.

**Comment by bogdanChernichenko** [comment]
specflow-reporter not recognized as a command...what I am doing wrong? Tool has been installed successfully

**Comment by alexmalimon** [comment]
> specflow-reporter not recognized as a command...

Sorry, my bad. It should be `specflow-report`

**Comment by bogdanChernichenko** [comment]
Ty for help, it worked
